kind: Pod
apiVersion: v1
metadata:
  name: labelspod
  labels:
    day: fri
    class: kubernetes
spec:
  containers:
    - name: c00
      image: centos 
      command: ["/bin/bash", "-c", "while true; do echo Hello-Sai; sleep 5 ; done"]
